// <auto-generated />
namespace TestIdentity.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makesureitsgonnabuild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makesureitsgonnabuild));
        
        string IMigrationMetadata.Id
        {
            get { return "201801240048257_make sure it's gonna build"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
